{
 "title": "Postgresql",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "DB queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Most commented movies",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"movieId\",\n  count(\"movieId\") AS \"count\"\nFROM comment\nWHERE\n  $__timeFilter(\"createdAt\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Comments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"createdAt\",$__interval),\n  count(id) AS \"id\"\nFROM comment\nWHERE\n  $__timeFilter(\"createdAt\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DB: Views",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "views" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id) AS \"count\"\nFROM view\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DB: Wishlist",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wishes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id) AS \"movieId\"\nFROM view\nORDER BY 1"
    }
   ]
  }
 ]
}