name: lint

on:
  push:
    branches-ignore: [master]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master]

jobs:
  lint:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    # if: ${{ !env.ACT }}
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0
    - 
      name: Run linter
      uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_WORKSPACE: apps/web
        JAVASCRIPT_DEFAULT_STYLE: prettier
        VALIDATE_JAVASCRIPT_STANDARD: false # We use prettier
        VALIDATE_TYPESCRIPT_STANDARD: false # We use prettier
        VALIDATE_KUBERNETES_KUBEVAL: false
        VALIDATE_JSCPD: false
        DEFAULT_BRANCH: main
        OUTPUT_DETAILS: detailed
        OUTPUT_FORMAT: tap
        # ACTIONS_RUNNER_DEBUG: true
    - 
      name: Upload Report as an artifact
      uses: actions/upload-artifact@master
      with:
        name: linter-report
        path: "${{ github.workspace }}/super-linter.report/"
